name: Deploy
on: [workflow_dispatch, push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: ls -lah ${{ secrets.DEST_PATH }}
            host: ${{ secrets.SSH_HOST_PRODUCTION }}
            port: ${{ secrets.SSH_PORT_PRODUCTION }}
            username: ${{ secrets.SSH_USER }}
            privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
#          run: |
#              rsync -a --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_PRODUCTION }}" -v . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_PRODUCTION }}:${{ secrets.DEST_PATH }}
